In [1]:
import numpy as np

In [2]:
X = np.array([[0, 1], [1, 0]])

print("X X†\n")
print(X.dot(X.T.conj()))

print("\nX† X\n")
print(X.T.conj().dot(X))

X X†

[[1 0]
 [0 1]]

X† X

[[1 0]
 [0 1]]


In [3]:
zero_ket = np.array([[1], [0]])

print("The norm of the state |0> before applying X = %f\n" % np.linalg.norm(zero_ket))
print("The norm of the state after applying X = %f" % np.linalg.norm(X.dot(zero_ket)))

The norm of the state |0> before applying X = 1.000000

The norm of the state after applying X = 1.000000


In [4]:
def mixed_state(densityMatrix, visibility):
    maximally_mixed_state = np.eye(4) / 2**2
    return (visibility * densityMatrix) + (1 - visibility) * maximally_mixed_state

øKet = np.array([[1], [0], [0], [1]]) / np.sqrt(2)
øBra = øKet.T.conj()

øRho = øKet.dot(øBra)
print('density matrix of |ø>\n\n', øRho)

density matrix of |ø>

 [[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]


In [5]:
print("Maximum visibility is a pure state:")
print(mixed_state(øRho, 1.0))

print("The state is still entangled with visibility 0.8:")
print(mixed_state(øRho, 0.5))

print("No coherence left:")
print(mixed_state(øRho, 0))

Maximum visibility is a pure state:
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]
The state is still entangled with visibility 0.8:
[[0.375 0.    0.    0.25 ]
 [0.    0.125 0.    0.   ]
 [0.    0.    0.125 0.   ]
 [0.25  0.    0.    0.375]]
No coherence left:
[[0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25]]


In [6]:

import matplotlib.pyplot as plt

temperatures = [.5, 5, 2000]
energies = np.linspace(0, 20, 100)

fig, ax = plt.subplots()

for i, T in enumerate(temperatures):
    probabilities = np.exp(-energies/T)
    Z = probabilities.sum()
    probabilities /= Z
    ax.plot(energies, probabilities, linewidth=3, label = "$T_" + str(i+1)+"$")

ax.set_xlim(0, 20); ax.set_ylim(0, 1.2 * probabilities.max())
ax.set_xticks([]); ax.set_yticks([])
ax.set_xlabel('Energy'); ax.set_ylabel('Probability'); ax.legend()